void twoSum(const double a, const double b, double *s_res, double *e_res);
void twoMultFMA(const double a, const double b, double *pi_res, double *e_res);
void vecSum(double *x, double *e_res, int in_out_size);
void vecSumErrBranch(double *e, int n, int m, double *f);
void vecSumErr(double *f, int n, double *g);
void renormalizationalgorithm(double x[], int size_of_x, double f[], int m);
void merge(double const *x, double const *y, double *z, int K, int L);
void addition(double *a, double *b, double *s, int length_a, int length_b, int length_result);
void multiplication(double *a, double *b, double *r, int sizea, int sizeb, int sizer);
void mult2(double *x, double *y, double *pi, int n, int m, int r);
